using System.Collections.Generic;

namespace Lara.Randomizers
{
    internal class FirstNameCollection
    {
        /// <summary>
        ///  Returns a list of first names based on the informed language.
        /// </summary>
        /// <param name="language">The language to consider when returning the list.</param>
        internal List<string> GetCollection(Language language)
        {
            return language switch
            {
                Language.EnUs => GetEnUS(),
                Language.PtBr => GetPtBR(),
                _ => GetEnUS(),
            };
        }

        /// <summary>
        /// Returns a list of names in EnUS.
        /// </summary>
        private List<string> GetEnUS()
        {
            return new List<string>
            {
                "Amanda",
                "Andy",
                "Angela",
                "Arielle",
                "Arthur",
                "Bella",
                "Ben",
                "Billy",
                "Bob",
                "Brad",
                "Brandon",
                "Brett",
                "Brittany",
                "Bronco",
                "Butterfly",
                "Carla",
                "Carter",
                "Catherine",
                "Cheryl",
                "Chester",
                "Chris",
                "Clark",
                "Conlan",
                "Corin",
                "Creagen",
                "Crystal",
                "Daniel",
                "Danny",
                "Darrell",
                "David",
                "Del",
                "DeLane",
                "Delta",
                "Diana",
                "Dick",
                "Donnie",
                "Elizabeth",
                "Eva",
                "Faye",
                "Gail",
                "Gauge (born",
                "Genesis",
                "George",
                "Georgia",
                "Gil",
                "Gina",
                "Hugh",
                "Jacob",
                "Jennifer",
                "Jerry",
                "Jessica",
                "Joey",
                "John",
                "Jonathan",
                "Josh",
                "Josie",
                "Julie",
                "Karmyn",
                "Karri",
                "Katherine",
                "Katy",
                "Kimberly",
                "Kirsten",
                "Kobe",
                "Larry",
                "Laurence",
                "Lawrence",
                "Maggie",
                "Malcolm",
                "Mandy",
                "Marjorie",
                "Mary",
                "Matt",
                "Maya",
                "Megan",
                "Mel",
                "Merian",
                "Mickey",
                "Monica",
                "Natalie",
                "Nicole",
                "Norman",
                "Rachel",
                "Raúl",
                "Rick",
                "Riley",
                "Robert",
                "Rodger",
                "Rudy",
                "Sarah",
                "Shannon",
                "Shea",
                "Sheryl",
                "Skyler",
                "Stephen",
                "Summer",
                "Tess",
                "Tom",
                "Tony",
                "Velia"
            };
        }

        /// <summary>
        /// Returns a list of names in PtBR.
        /// </summary>
        private List<string> GetPtBR()
        {
            return new List<string>
            {
                "Adriana",
                "Affonso",
                "Alexandre",
                "Alfredo",
                "Alice",
                "Alinne",
                "Almeida",
                "Ana",
                "Anderson",
                "Anita",
                "Antonio",
                "Antônio",
                "Artur",
                "Bete",
                "Betty",
                "Bruna",
                "Bruno",
                "Cândido",
                "Carlos",
                "Carmen",
                "Carolina",
                "Cauã",
                "Daniel",
                "Daniele",
                "Denise",
                "Dercy",
                "Eliane",
                "Emiliano",
                "Eronilde",
                "Eurico",
                "Fábio",
                "Fellipe",
                "Fernanda",
                "Francisca",
                "Giovanna",
                "Glória",
                "Grande",
                "Graziella",
                "Guilherme",
                "Hebe",
                "Hebert",
                "Hélio",
                "Igor",
                "Jaime",
                "Jéssica",
                "João",
                "Jonas",
                "José",
                "Juliana",
                "Kelvin",
                "Lasar",
                "Lázaro",
                "Leandro",
                "Leonardo",
                "Lima",
                "Lina",
                "Lucélia",
                "Lúcio",
                "Lygia",
                "Malu",
                "Manabu",
                "Marcio",
                "Marco",
                "Marcos",
                "Maria",
                "Matheus",
                "Mauricio",
                "Miguel",
                "Morena",
                "Moysés",
                "Murilo",
                "Natália",
                "Naza,",
                "Nivaldo",
                "Oscar",
                "Oswaldo",
                "Paola",
                "Paulo",
                "Raul",
                "Raw",
                "Regina",
                "Renato",
                "Reynaldo",
                "Ricardo",
                "Rita",
                "Roberto",
                "Rodrigo",
                "Ronald",
                "Ruy",
                "Sandy",
                "Selton",
                "Sidnei",
                "Solange",
                "Sônia",
                "Taiguara",
                "Taís",
                "Tarcisio",
                "Tarsila",
                "Teresa",
                "Vera",
                "Victor"
            };
        }
    }
}
