using System.Collections.Generic;

namespace Lara.Randomizers
{
    internal class CityCollection
    {
        /// <summary>
        ///  Returns a list of Cities. Examples: "New York", "San Francisco", etc..
        /// </summary>
        /// <param name="language">The language to consider when returning the list.</param>
        internal List<string> GetCollection(Language language)
        {
            return language switch
            {
                Language.EnUs => GetEnUs(),
                Language.PtBr => GetPtBr(),
                _ => GetEnUs(),
            };
        }

        /// <summary>
        /// Returns a list of Cities in EnUs.
        /// </summary>
        private List<string> GetEnUs()
        {
            return new List<string>
            {
               "Albuquerque",
                "Anaheim",
                "Anchorage",
                "Arlington",
                "Atlanta",
                "Aurora",
                "Austin",
                "Bakersfield",
                "Baltimore",
                "Baton Rouge",
                "Boise",
                "Boston",
                "Buffalo",
                "Chandler",
                "Charlotte",
                "Chesapeake",
                "Chicago",
                "Chula Vista",
                "Cincinnati",
                "Cleveland",
                "Colorado Springs",
                "Columbus",
                "Dallas",
                "Denver",
                "Des Moines",
                "Detroit",
                "Durham",
                "El Paso",
                "Fort Wayne",
                "Fort Worth",
                "Fremont",
                "Fresno",
                "Garland",
                "Gilbert",
                "Glendale",
                "Greensboro",
                "Henderson",
                "Hialeah",
                "Honolulu",
                "Houston",
                "Indianapolis",
                "Irvine",
                "Irving",
                "Jacksonville",
                "Jersey City",
                "Kansas City",
                "Laredo",
                "Las Vegas",
                "Lexington",
                "Lincoln",
                "Long Beach",
                "Los Angeles",
                "Louisville",
                "Lubbock",
                "Madison",
                "Memphis",
                "Mesa",
                "Miami",
                "Milwaukee",
                "Minneapolis",
                "Nashville",
                "New Orleans",
                "New York",
                "Newark",
                "Norfolk",
                "North Las Vegas",
                "Oakland",
                "Oklahoma City",
                "Omaha",
                "Orlando",
                "Philadelphia",
                "Phoenix",
                "Pittsburgh",
                "Plano",
                "Portland",
                "Raleigh",
                "Reno",
                "Richmond",
                "Riverside",
                "Sacramento",
                "Saint Paul",
                "San Antonio",
                "San Diego",
                "San Francisco",
                "San Jose",
                "Santa Ana",
                "Scottsdale",
                "Seattle",
                "Spokane",
                "St. Louis[m]",
                "St. Petersburg",
                "Stockton",
                "Tampa",
                "Toledo",
                "Tucson",
                "Tulsa",
                "Virginia Beach",
                "Washington",
                "Wichita",
                "Winston-Salem"
            };
        }

        /// <summary>
        /// Returns a list of Cities in PtBr.
        /// </summary>
        private List<string> GetPtBr()
        {
            return new List<string>
            {
                "Ananindeua",
                "Anápolis",
                "Aparecida de Goiânia",
                "Aracaju",
                "Barueri",
                "Bauru",
                "Belém",
                "Belford Roxo",
                "Belo Horizonte",
                "Betim",
                "Blumenau",
                "Boa Vista",
                "Brasília",
                "Camaçari",
                "Campina Grande",
                "Campinas",
                "Campo Grande",
                "Canoas",
                "Carapicuíba",
                "Cariacica",
                "Cascavel",
                "Caucaia",
                "Caxias do Sul",
                "Contagem",
                "Cuiabá",
                "Curitiba",
                "Diadema",
                "Duque de Caxias",
                "Embu das Artes",
                "Feira de Santana",
                "Florianópolis",
                "Fortaleza",
                "Franca",
                "Goiânia",
                "Governador Valadares",
                "Gravataí",
                "Guarujá",
                "Guarulhos",
                "Ipatinga",
                "Itaquaquecetuba",
                "Jaboatão dos Guararapes",
                "João Pessoa",
                "Joinville",
                "Juazeiro do Norte",
                "Juiz de Fora",
                "Jundiaí",
                "Limeira",
                "Londrina",
                "Macapá",
                "Maceió",
                "Manaus",
                "Marabá",
                "Maringá",
                "Mauá",
                "Mogi das Cruzes",
                "Montes Claros",
                "Mossoró",
                "Natal",
                "Niterói",
                "Nova Iguaçu",
                "Olinda",
                "Osasco",
                "Palmas",
                "Paulista",
                "Pelotas",
                "Petrolina",
                "Petrópolis",
                "Piracicaba",
                "Ponta Grossa",
                "Porto Alegre",
                "Porto Velho",
                "Praia Grande",
                "Recife",
                "Ribeirão das Neves",
                "Ribeirão Preto",
                "Rio Branco",
                "Rio de Janeiro",
                "Salvador",
                "Santa Maria",
                "Santarém",
                "Santo André",
                "Santos",
                "São Bernardo do Campo",
                "São Gonçalo",
                "São João de Meriti",
                "São José do Rio Preto",
                "São José dos Campos",
                "São José dos Pinhais",
                "São Luís",
                "São Paulo",
                "São Vicente",
                "Serra",
                "Sorocaba",
                "Sumaré",
                "Suzano",
                "Taboão da Serra",
                "Taubaté",
                "Teresina",
                "Uberaba",
                "Uberlândia"
            };
        }
    }
}
