using System.Collections.Generic;

namespace Lara.Randomizers
{
    internal class BrandCollection
    {
        /// <summary>
        ///  Returns a list of Brands.
        /// </summary>
        internal List<string> GetCollection()
        {
            return new List<string>
            {
                "3M",
                "Accenture",
                "Adidas",
                "Adobe",
                "Allianz",
                "Amazon",
                "American Express",
                "Apple",
                "Audi",
                "BMW",
                "Budweiser",
                "Canon",
                "Cartier",
                "Caterpillar",
                "Chery",
                "Cisco",
                "CNN",
                "Coca Cola",
                "Colgate",
                "Corona",
                "Danone",
                "Dell",
                "DHL",
                "Dior",
                "Discovery",
                "Disney",
                "eBay",
                "FedEx",
                "Ferrari",
                "Ford",
                "Fox",
                "General Eletric",
                "Gilette",
                "Google",
                "Gucci",
                "Harley Davidson",
                "HBO",
                "Heineken",
                "Honda",
                "HP",
                "HSBC",
                "Huawei",
                "Hyunday",
                "IBM",
                "IKEA",
                "Intel",
                "Jack Daniel's",
                "Kellogg's",
                "KIA",
                "Land Rover",
                "Lego",
                "LinkedIn",
                "Loreal",
                "Louis Vuitton",
                "Mastercard",
                "McDonalds",
                "Mercedes",
                "Microsoft",
                "Nescafé",
                "Nestle",
                "Netflix",
                "Nike",
                "Nintendo",
                "Nissan",
                "Oracle",
                "Pampers",
                "Panasonic",
                "PayPal",
                "Pepsi",
                "Philips",
                "Porsche",
                "Prada",
                "Prada",
                "Salesforce",
                "Samsung",
                "Santander",
                "SAP",
                "Shell",
                "Siemens",
                "Sony",
                "Spotify",
                "Starbucks",
                "Toyota",
                "Uber",
                "Universal Studios",
                "UPS",
                "Visa",
                "Volkswagen",
                "Xiaomi",
                "Yamaha"
            };
        }
    }
}
