using System.Collections.Generic;

namespace Lara.Randomizers
{
    internal class LoremIpsumCollection
    {
        /// <summary>
        ///  Returns a list of Lorem Upsum paragraphs.
        /// </summary>
        internal List<string> GetCollection()
        {
            return new List<string>
            {
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tristique, enim ut viverra feugiat, felis lorem interdum quam, vel elementum sem nisl quis erat. Suspendisse et ultrices enim, vel vehicula lorem. Ut at urna sem. Etiam iaculis felis ut posuere rhoncus. Donec viverra tempus lorem nec blandit. Curabitur placerat magna at sollicitudin accumsan. In hac habitasse platea dictumst. Fusce lacinia, urna in ultrices iaculis, nibh nisi egestas massa, sed mollis nulla tortor id sapien. Suspendisse eget rhoncus nunc, id bibendum nibh. Vestibulum a purus a enim tristique vestibulum. In aliquet porttitor sapien, quis tristique velit finibus ac. Praesent suscipit vestibulum nibh, a commodo tellus.",
                "Praesent ornare turpis ac justo molestie scelerisque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce venenatis libero odio, non pretium mauris bibendum quis. Pellentesque vitae odio sit amet lacus fringilla interdum in eget felis. Morbi nulla orci, sollicitudin sit amet orci quis, fringilla bibendum libero. Morbi tincidunt ipsum ut eros ornare, id porttitor diam imperdiet. Suspendisse eget ante placerat justo eleifend pellentesque.",
                "Maecenas eu purus vehicula, tempor augue ac, ultricies erat. Pellentesque lobortis nibh dui. Phasellus non dui facilisis, varius elit eget, maximus metus. Morbi eget molestie mi. Sed pellentesque mauris quis mauris gravida, vitae volutpat est dictum. Morbi ornare ullamcorper lorem, a imperdiet erat laoreet facilisis. Aenean quis tincidunt metus. Maecenas quis tellus sit amet ligula porta efficitur. Suspendisse sit amet pellentesque dolor. Aliquam erat volutpat. Curabitur a dui sit amet lorem lacinia ultricies et sit amet tortor. Sed faucibus sit amet elit vitae eleifend.",
                "Quisque sem elit, cursus nec interdum in, lobortis sit amet nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at risus eu lectus blandit tempor vitae mollis nunc. Curabitur eu velit ut velit ullamcorper lacinia non vitae ipsum. Cras eu odio tempor, porta sapien nec, semper nunc. Duis ut risus gravida, lacinia nulla vel, consectetur magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam sollicitudin diam ac finibus sollicitudin. Pellentesque sagittis massa eget mattis vulputate.",
                "Maecenas tristique semper ex, at accumsan lorem consequat sed. Fusce at laoreet ex, in rutrum tortor. Nullam sollicitudin tincidunt efficitur. Nam eget ante eget augue dictum porta. Aliquam mollis tortor sapien, quis vehicula orci euismod congue. Ut accumsan pretium mollis. Aliquam fermentum cursus velit. Cras auctor nibh sit amet magna convallis fringilla. Integer aliquam venenatis sollicitudin. Sed ultricies ante arcu, at laoreet augue rhoncus sed. Donec euismod dolor nec vulputate semper. Donec auctor, turpis at varius tristique, ipsum velit eleifend nulla, eu malesuada magna neque eu turpis.",
                "Mauris condimentum mollis lectus vitae aliquet. Aliquam sed bibendum dui. Morbi interdum dui sit amet dui lacinia varius. Mauris imperdiet sodales libero a hendrerit. Donec sit amet magna in augue ullamcorper tempor et sed nisl. In dolor orci, maximus vitae ornare iaculis, euismod quis nunc. Aliquam ac mi urna. Curabitur a dui vitae nisi molestie lacinia et at neque. Curabitur porta tellus sed lorem consectetur, faucibus facilisis nulla scelerisque. Maecenas in blandit nisl, quis luctus odio. Proin fringilla convallis magna condimentum accumsan. Curabitur gravida sem auctor dui auctor, vitae luctus justo ultricies. Integer condimentum lectus ut tristique dapibus. Nunc tincidunt dolor vitae euismod placerat. Integer suscipit finibus justo vel rhoncus.",
                "estibulum consequat commodo volutpat. Maecenas mollis, ante tempus fermentum euismod, tellus purus dapibus turpis, a luctus neque tortor vitae quam. Pellentesque ipsum leo, pretium ac suscipit sed, efficitur vel urna. Quisque efficitur sodales lectus, sed sagittis lorem commodo non. Nam volutpat semper mauris sodales consectetur. Vestibulum ac ex sed purus euismod vehicula eu sit amet turpis. Quisque aliquet, mi a maximus sagittis, nibh ante tincidunt erat, a dictum risus diam et risus. Suspendisse ornare mattis ligula quis consequat. Etiam sed nulla justo. Pellentesque diam tortor, dignissim sit amet magna sit amet, venenatis porta diam. Pellentesque faucibus, tortor id pretium varius, lectus ipsum egestas nisi, at molestie orci metus et nunc. Fusce maximus diam non risus pretium faucibus eget eleifend ante. Aenean egestas in nibh ac mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc efficitur aliquet enim at vestibulum. Suspendisse vel faucibus enim.",
                "Duis placerat semper suscipit. Aliquam mauris felis, accumsan vel ullamcorper id, suscipit ut risus. Nunc in massa lectus. Etiam feugiat massa ut sapien faucibus convallis. Aliquam interdum quam vitae sem vehicula consequat. Donec elementum tempus mauris, eu sodales ipsum ornare ut. Donec sollicitudin elementum neque, at malesuada libero rhoncus eu. In commodo fermentum arcu, vitae tristique dolor volutpat eu. Curabitur euismod ligula felis, sit amet tristique odio sodales ut.",
                "Suspendisse blandit, nibh ut lacinia aliquam, lorem metus laoreet diam, eget faucibus orci risus eu tellus. Quisque eget ante sapien. Praesent viverra in lacus non rhoncus. Cras euismod condimentum eros sed laoreet. Mauris vel egestas lectus. Duis gravida sagittis tempor. Mauris quis ultrices orci. Fusce eu placerat dui, nec blandit quam. Sed eget suscipit est. In hac habitasse platea dictumst. Curabitur sem diam, semper quis urna id, lacinia rutrum orci.",
                "Aenean lorem nulla, bibendum eget hendrerit at, commodo et mauris. Praesent volutpat sodales magna nec pulvinar. Proin auctor a est sed suscipit. Vestibulum leo ligula, tempus congue ullamcorper non, dignissim a lacus. Quisque laoreet neque sit amet placerat luctus. Mauris velit neque, tempor eu commodo a, luctus dictum orci. Suspendisse at leo pretium, vehicula massa sed, porta mi. Mauris at lacinia odio."
            };
        }
    }
}
